version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.7.0
    hostname: zookeeper
    ports:
        - 2181:2181
    environment:
        ZOO_MY_ID: 1
    networks:
      - zookeeper
  zoonavigator:
    image: elkozmon/zoonavigator
    hostname: zoonavigator
    ports:
        - 9000:9000
    networks:
      - zookeeper
volumes:
  db_data: {}

networks:
  zookeeper:
    driver: bridge
